import type { Announcement, AppNotification, EventApplication, EventReport, SchoolEvent, User } from "./types";

export const demoUser: User = {
  id: 1,
  fullName: "Мира Кенжебек",
  email: "mira@school.test",
  className: "8A",
  role: "student"
};

export const mockAnnouncements: Announcement[] = [
  {
    id: 1,
    title: "Неделя науки начинается в понедельник",
    titleKz: "Ғылым апталығы дүйсенбіде басталады",
    content: "Открываются лабораторные сессии, дебаты, выставка проектов и командные STEM-челленджи.",
    contentKz: "Зертханалық сессиялар, дебаттар, жобалар көрмесі және командалық STEM-челлендждер басталады.",
    category: "school-wide",
    priority: "important",
    imageUrl: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80",
    targetClasses: [],
    createdAt: "2026-04-18T08:00:00+00:00"
  },
  {
    id: 2,
    title: "Брифинг для 8-х классов перед поездкой в музей",
    titleKz: "8-сыныптарға музейге бару алдындағы брифинг",
    content: "Ученики 8A и 8B собираются в актовом зале после второго урока.",
    contentKz: "8A және 8B оқушылары екінші сабақтан кейін акт залында жиналады.",
    category: "class-specific",
    priority: "normal",
    targetClasses: ["8A", "8B"],
    createdAt: "2026-04-18T09:30:00+00:00"
  },
  {
    id: 3,
    title: "Открыт набор в ученический совет",
    titleKz: "Оқушылар кеңесіне қабылдау ашылды",
    content: "Если хочешь помогать с мероприятиями и улучшать школьную жизнь, отправь заявку до пятницы.",
    contentKz: "Іс-шараларға көмектесіп, мектеп өмірін жақсартқың келсе, жұмаға дейін өтінім жібер.",
    category: "opportunity",
    priority: "important",
    targetClasses: ["9A", "10B", "11A"],
    createdAt: "2026-04-17T11:00:00+00:00"
  },
  {
    id: 4,
    title: "Обновлен график консультаций перед олимпиадами",
    titleKz: "Олимпиада алдындағы кеңес беру кестесі жаңартылды",
    content: "Добавлены консультации по математике, биологии и английскому языку.",
    contentKz: "Математика, биология және ағылшын тілі бойынша қосымша кеңестер қосылды.",
    category: "school-wide",
    priority: "normal",
    targetClasses: [],
    createdAt: "2026-04-16T14:00:00+00:00"
  },
  {
    id: 5,
    title: "Волонтерская команда ищет помощников",
    titleKz: "Волонтерлік команда көмекшілер іздейді",
    content: "Нужны ученики для помощи на благотворительной ярмарке и встрече гостей.",
    contentKz: "Қайырымдылық жәрмеңкесіне және қонақтарды қарсы алуға оқушылар қажет.",
    category: "opportunity",
    priority: "normal",
    targetClasses: ["7A", "7B", "8A", "8B", "9A"],
    createdAt: "2026-04-15T10:15:00+00:00"
  },
  {
    id: 6,
    title: "Тихая зона в библиотеке во время экзаменов",
    titleKz: "Емтихан кезінде кітапханада тыныш аймақ",
    content: "С 22 апреля библиотека открывает отдельную зону для подготовки и самостоятельной работы.",
    contentKz: "22 сәуірден бастап кітапханада дайындық пен жеке жұмысқа арналған арнайы аймақ ашылады.",
    category: "school-wide",
    priority: "normal",
    targetClasses: [],
    createdAt: "2026-04-14T08:40:00+00:00"
  },
  {
    id: 7,
    title: "Классные руководители обновили списки проектов",
    titleKz: "Сынып жетекшілері жобалар тізімін жаңартты",
    content: "Проверь свой класс: некоторые проектные группы поменяли время встреч.",
    contentKz: "Өз сыныбыңызды тексеріңіз: кейбір жобалық топтардың кездесу уақыты өзгерді.",
    category: "class-specific",
    priority: "important",
    targetClasses: ["8A", "9A", "10B"],
    createdAt: "2026-04-13T13:20:00+00:00"
  }
];

export const mockEvents: SchoolEvent[] = [
  {
    id: 1,
    title: "Научная ярмарка проектов",
    titleKz: "Ғылыми жобалар жәрмеңкесі",
    shortDescription: "Презентация экспериментов, прототипов и исследовательских стендов.",
    shortDescriptionKz: "Эксперименттер, прототиптер және зерттеу стендтері таныстырылады.",
    fullDescription: "Ученики могут выступить как участники или прийти зрителями. Из-за вместимости зала зрительская регистрация открыта только для отдельных классов.",
    fullDescriptionKz: "Оқушылар қатысушы ретінде қатыса алады немесе көрермен бола алады. Зал сыйымдылығына байланысты көрермен тіркелуі тек кейбір сыныптарға ашық.",
    date: "2026-05-02",
    startTime: "14:00",
    endTime: "17:00",
    location: "Главный зал",
    locationKz: "Бас зал",
    category: "science",
    organizer: "STEM-клуб",
    organizerKz: "STEM клубы",
    coverImage: "https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-29T18:00:00+00:00",
    participantCapacity: 24,
    spectatorCapacity: 80,
    participantApprovedCount: 8,
    spectatorApprovedCount: 39,
    allowedSpectatorClasses: ["8A", "8B", "9A"],
    viewerCanSpectate: true,
    tags: ["STEM", "исследования", "команда"],
    status: "upcoming",
    featured: true
  },
  {
    id: 2,
    title: "Кубок классов по баскетболу",
    titleKz: "Сыныптар арасындағы баскетбол кубогы",
    shortDescription: "Дружеский турнир команд после уроков.",
    shortDescriptionKz: "Сабақтан кейінгі достық командалық турнир.",
    fullDescription: "Классы собирают команды, болельщики поддерживают с трибун. Зрительская регистрация открыта всем.",
    fullDescriptionKz: "Сыныптар команда жинайды, жанкүйерлер трибунадан қолдайды. Көрермен тіркелуі барлығына ашық.",
    date: "2026-04-24",
    startTime: "15:30",
    endTime: "18:00",
    location: "Спортзал",
    locationKz: "Спорт залы",
    category: "sports",
    organizer: "Кафедра физкультуры",
    organizerKz: "Дене шынықтыру кафедрасы",
    coverImage: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-22T17:00:00+00:00",
    participantCapacity: 60,
    spectatorCapacity: 200,
    participantApprovedCount: 34,
    spectatorApprovedCount: 121,
    allowedSpectatorClasses: [],
    viewerCanSpectate: true,
    tags: ["спорт", "команды"],
    status: "upcoming",
    featured: true
  },
  {
    id: 3,
    title: "Дебатный вечер: города будущего",
    titleKz: "Дебат кеші: болашақ қалалары",
    shortDescription: "Структурные дебаты с голосованием зрителей.",
    shortDescriptionKz: "Көрермен дауыс беруімен өтетін құрылымды дебат.",
    fullDescription: "Подготовь аргументы, выступи спикером или зарегистрируйся зрителем, если твой класс в списке.",
    fullDescriptionKz: "Дәлелдер дайындап, спикер бол немесе сыныбың тізімде болса көрермен ретінде тіркел.",
    date: "2026-05-06",
    startTime: "16:00",
    endTime: "18:00",
    location: "Библиотечный форум",
    locationKz: "Кітапхана форумы",
    category: "culture",
    organizer: "Дебатное общество",
    organizerKz: "Дебат қоғамы",
    registrationOpen: true,
    registrationDeadline: "2026-05-03T16:00:00+00:00",
    participantCapacity: 16,
    spectatorCapacity: 70,
    participantApprovedCount: 10,
    spectatorApprovedCount: 28,
    allowedSpectatorClasses: ["9A", "10B", "11A"],
    viewerCanSpectate: false,
    tags: ["дебаты", "лидерство"],
    status: "upcoming",
    featured: false
  },
  {
    id: 4,
    title: "Музыкальный вечер Lyceum Unplugged",
    titleKz: "Lyceum Unplugged музыкалық кеші",
    shortDescription: "Акустические выступления учеников и камерная атмосфера.",
    shortDescriptionKz: "Оқушылардың акустикалық өнер көрсетуі және жайлы атмосфера.",
    fullDescription: "Вечер для вокалистов, инструменталистов и зрителей. Количество мест ограничено.",
    fullDescriptionKz: "Вокалистер, аспапта ойнаушылар және көрермендерге арналған кеш. Орын саны шектеулі.",
    date: "2026-04-28",
    startTime: "17:00",
    endTime: "19:00",
    location: "Актовый зал",
    locationKz: "Акт залы",
    category: "culture",
    organizer: "Музыкальный клуб",
    organizerKz: "Музыка клубы",
    coverImage: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-25T18:00:00+00:00",
    participantCapacity: 18,
    spectatorCapacity: 90,
    participantApprovedCount: 12,
    spectatorApprovedCount: 54,
    allowedSpectatorClasses: ["7A", "8A", "8B", "10B"],
    viewerCanSpectate: true,
    tags: ["музыка", "сцена"],
    status: "upcoming",
    featured: false
  },
  {
    id: 5,
    title: "Эко-двор: весенняя посадка",
    titleKz: "Эко-аула: көктемгі отырғызу",
    shortDescription: "Команды классов обновят школьный двор и клумбы.",
    shortDescriptionKz: "Сынып командалары мектеп ауласы мен гүлзарларды жаңартады.",
    fullDescription: "Практическая волонтерская активность: посадка цветов, маркировка зон и оформление графика ухода.",
    fullDescriptionKz: "Практикалық волонтерлік белсенділік: гүл отырғызу, аймақтарды белгілеу және күтім кестесін жасау.",
    date: "2026-04-26",
    startTime: "12:30",
    endTime: "15:00",
    location: "Школьный двор",
    locationKz: "Мектеп ауласы",
    category: "community",
    organizer: "Eco Team",
    organizerKz: "Eco Team",
    coverImage: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-23T18:00:00+00:00",
    participantCapacity: 40,
    spectatorCapacity: 20,
    participantApprovedCount: 26,
    spectatorApprovedCount: 4,
    allowedSpectatorClasses: ["8A", "9A"],
    viewerCanSpectate: true,
    tags: ["волонтерство", "экология"],
    status: "upcoming",
    featured: false
  },
  {
    id: 6,
    title: "Хакатон школьных сервисов",
    titleKz: "Мектеп сервистері хакатоны",
    shortDescription: "Мини-команды проектируют цифровые решения для школы.",
    shortDescriptionKz: "Шағын командалар мектепке арналған цифрлық шешімдер жасайды.",
    fullDescription: "За 4 часа команды предложат идею, прототип и короткую презентацию. Зрители допускаются только из старших классов.",
    fullDescriptionKz: "4 сағат ішінде командалар идея, прототип және қысқа презентация ұсынады. Көрермендер тек жоғары сыныптардан.",
    date: "2026-05-11",
    startTime: "13:00",
    endTime: "17:30",
    location: "IT-кабинет",
    locationKz: "IT кабинеті",
    category: "science",
    organizer: "IT Lab",
    organizerKz: "IT Lab",
    coverImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-05-08T18:00:00+00:00",
    participantCapacity: 30,
    spectatorCapacity: 35,
    participantApprovedCount: 18,
    spectatorApprovedCount: 12,
    allowedSpectatorClasses: ["10B", "11A"],
    viewerCanSpectate: false,
    tags: ["IT", "прототип"],
    status: "upcoming",
    featured: true
  },
  {
    id: 7,
    title: "Благотворительная ярмарка",
    titleKz: "Қайырымдылық жәрмеңкесі",
    shortDescription: "Классы готовят стенды, открытки и мини-активности.",
    shortDescriptionKz: "Сыныптар стендтер, ашықхаттар және шағын белсенділіктер дайындайды.",
    fullDescription: "Средства пойдут на школьные социальные проекты. Можно участвовать с классом или помогать как волонтер.",
    fullDescriptionKz: "Қаражат мектептің әлеуметтік жобаларына бағытталады. Сыныппен қатысуға немесе волонтер болуға болады.",
    date: "2026-05-15",
    startTime: "11:00",
    endTime: "14:00",
    location: "Холл первого этажа",
    locationKz: "Бірінші қабат холы",
    category: "community",
    organizer: "Ученический совет",
    organizerKz: "Оқушылар кеңесі",
    coverImage: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-05-12T18:00:00+00:00",
    participantCapacity: 70,
    spectatorCapacity: 250,
    participantApprovedCount: 41,
    spectatorApprovedCount: 88,
    allowedSpectatorClasses: [],
    viewerCanSpectate: true,
    tags: ["волонтерство", "ярмарка"],
    status: "upcoming",
    featured: false
  },
  {
    id: 8,
    title: "Турнир по шахматам",
    titleKz: "Шахмат турнирі",
    shortDescription: "Личный зачет и командные очки для классов.",
    shortDescriptionKz: "Жеке есеп және сыныптарға командалық ұпайлар.",
    fullDescription: "Турнир пройдет по швейцарской системе. Зрительская зона небольшая, поэтому доступна только 7-8 классам.",
    fullDescriptionKz: "Турнир швейцариялық жүйе бойынша өтеді. Көрермен аймағы шағын, сондықтан тек 7-8 сыныптарға қолжетімді.",
    date: "2026-05-20",
    startTime: "15:00",
    endTime: "18:00",
    location: "Кабинет 204",
    locationKz: "204 кабинет",
    category: "science",
    organizer: "Шахматный клуб",
    organizerKz: "Шахмат клубы",
    registrationOpen: true,
    registrationDeadline: "2026-05-17T18:00:00+00:00",
    participantCapacity: 32,
    spectatorCapacity: 24,
    participantApprovedCount: 20,
    spectatorApprovedCount: 11,
    allowedSpectatorClasses: ["7A", "7B", "8A", "8B"],
    viewerCanSpectate: true,
    tags: ["логика", "турнир"],
    status: "upcoming",
    featured: false
  }
];

export const mockReports: EventReport[] = [
  {
    id: 1,
    eventId: 10,
    title: "Эко-день превратил двор в зеленую зону",
    titleKz: "Эко-күн ауланы жасыл аймаққа айналдырды",
    summary: "Ученики посадили 120 цветов, установили 6 станций переработки и составили график ухода.",
    summaryKz: "Оқушылар 120 гүл отырғызып, 6 қайта өңдеу станциясын орнатып, күтім кестесін жасады.",
    results: ["120 цветов посажено", "6 станций переработки установлено", "14 волонтеров отмечены"],
    resultsKz: ["120 гүл отырғызылды", "6 қайта өңдеу станциясы орнатылды", "14 волонтер марапатталды"],
    highlights: ["7C подготовил план двора", "10B помог с логистикой", "Eco Team запустила дежурства"],
    highlightsKz: ["7C аула жоспарын дайындады", "10B логистикаға көмектесті", "Eco Team кезекшілік бастады"],
    gallery: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=80"],
    quote: "Маленькие изменения становятся культурой, когда их видит вся школа.",
    quoteKz: "Кішкентай өзгерістерді бүкіл мектеп көргенде, олар мәдениетке айналады.",
    publishedAt: "2026-04-10T10:00:00+00:00"
  },
  {
    id: 2,
    eventId: 11,
    title: "Дебаты помогли выбрать идеи для школьного двора",
    titleKz: "Дебаттар мектеп ауласына идея таңдауға көмектесті",
    summary: "Команды обсудили безопасность, зоны отдыха и навигацию по школе.",
    summaryKz: "Командалар қауіпсіздік, демалыс аймақтары және мектеп навигациясын талқылады.",
    results: ["Победила команда 9A", "42 зрителя проголосовали", "3 идеи переданы администрации"],
    resultsKz: ["9A командасы жеңді", "42 көрермен дауыс берді", "3 идея әкімшілікке берілді"],
    highlights: ["Лучший аргумент — 10B", "Самая сильная речь — 9A"],
    highlightsKz: ["Үздік дәлел — 10B", "Ең мықты сөз — 9A"],
    gallery: ["https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80"],
    quote: "Хорошая идея становится сильнее, когда ее проверяют вопросами.",
    quoteKz: "Жақсы идея сұрақтар арқылы тексерілгенде күшейеді.",
    publishedAt: "2026-04-08T09:00:00+00:00"
  },
  {
    id: 3,
    eventId: 12,
    title: "Книжный обмен собрал 300 книг",
    titleKz: "Кітап алмасу 300 кітап жинады",
    summary: "Ученики принесли книги, оформили стенды рекомендаций и запустили мини-букклубы.",
    summaryKz: "Оқушылар кітап әкеліп, ұсыныс стендтерін жасап, шағын кітап клубтарын бастады.",
    results: ["300 книг обменяно", "5 новых букклубов", "18 рекомендаций опубликовано"],
    resultsKz: ["300 кітап алмастырылды", "5 жаңа кітап клубы", "18 ұсыныс жарияланды"],
    highlights: ["8A оформил лучший стенд", "7B собрал самую большую подборку"],
    highlightsKz: ["8A үздік стенд жасады", "7B ең үлкен топтама жинады"],
    gallery: ["https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80"],
    publishedAt: "2026-04-02T12:00:00+00:00"
  }
];

export const mockApplications: EventApplication[] = [
  { id: 1, userId: 1, eventId: 1, applicationType: "spectator", status: "approved", createdAt: "2026-04-18T12:00:00+00:00", event: mockEvents[0] },
  { id: 2, userId: 1, eventId: 2, applicationType: "participant", status: "pending", createdAt: "2026-04-17T15:00:00+00:00", event: mockEvents[1] },
  { id: 3, userId: 1, eventId: 4, applicationType: "spectator", status: "approved", createdAt: "2026-04-16T09:30:00+00:00", event: mockEvents[3] },
  { id: 4, userId: 1, eventId: 5, applicationType: "participant", status: "waitlisted", createdAt: "2026-04-15T11:20:00+00:00", event: mockEvents[4] },
  { id: 5, userId: 1, eventId: 8, applicationType: "spectator", status: "pending", createdAt: "2026-04-14T16:10:00+00:00", event: mockEvents[7] }
];

export const mockNotifications: AppNotification[] = [
  { id: 1, userId: 1, title: "Заявка на научную ярмарку одобрена", titleKz: "Ғылыми жәрмеңкеге өтінім мақұлданды", message: "Ты зарегистрирована как зритель. Не забудь прийти за 10 минут до начала.", messageKz: "Сіз көрермен ретінде тіркелдіңіз. Басталардан 10 минут бұрын келуді ұмытпаңыз.", isRead: false, type: "application", createdAt: "2026-04-18T13:00:00+00:00" },
  { id: 2, userId: 1, title: "Баскетбольный кубок закрывается завтра", titleKz: "Баскетбол кубогына тіркелу ертең жабылады", message: "Если хочешь участвовать, отправь заявку сегодня.", messageKz: "Қатысқыңыз келсе, бүгін өтінім жіберіңіз.", isRead: false, type: "event", createdAt: "2026-04-18T09:00:00+00:00" },
  { id: 3, userId: 1, title: "Опубликован отчет Eco Day", titleKz: "Eco Day есебі жарияланды", message: "Посмотри результаты и лучшие моменты прошедшего события.", messageKz: "Өткен іс-шараның нәтижелері мен үздік сәттерін қараңыз.", isRead: true, type: "report", createdAt: "2026-04-10T12:00:00+00:00" },
  { id: 4, userId: 1, title: "Музыкальный вечер открыт для 8A", titleKz: "Музыкалық кеш 8A үшін ашық", message: "Ты можешь зарегистрироваться зрителем или участником.", messageKz: "Сіз көрермен немесе қатысушы ретінде тіркеле аласыз.", isRead: false, type: "event", createdAt: "2026-04-16T10:00:00+00:00" }
];
