import type { Announcement, AppNotification, EventApplication, EventReport, SchoolEvent, User } from "./types";

export const demoUser: User = {
  id: 1,
  fullName: "Мира Кенжебек",
  email: "mira@school.test",
  className: "8A",
  role: "student"
};

export const mockAnnouncements: Announcement[] = [
  {
    id: 1,
    title: "Неделя науки начинается в понедельник",
    titleKz: "Ғылым апталығы дүйсенбіде басталады",
    content: "Открываются лабораторные сессии, дебаты, выставка проектов и командные STEM-челленджи.",
    contentKz: "Зертханалық сессиялар, дебаттар, жобалар көрмесі және командалық STEM-челлендждер басталады.",
    category: "school-wide",
    priority: "important",
    imageUrl: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80",
    targetClasses: [],
    createdAt: "2026-04-18T08:00:00+00:00"
  },
  {
    id: 2,
    title: "Брифинг для 8-х классов перед поездкой в музей",
    titleKz: "8-сыныптарға музейге бару алдындағы брифинг",
    content: "Ученики 8A и 8B собираются в актовом зале после второго урока.",
    contentKz: "8A және 8B оқушылары екінші сабақтан кейін акт залында жиналады.",
    category: "class-specific",
    priority: "normal",
    targetClasses: ["8A", "8B"],
    createdAt: "2026-04-18T09:30:00+00:00"
  },
  {
    id: 3,
    title: "Открыт набор в ученический совет",
    titleKz: "Оқушылар кеңесіне қабылдау ашылды",
    content: "Если хочешь помогать с мероприятиями и улучшать школьную жизнь, отправь заявку до пятницы.",
    contentKz: "Іс-шараларға көмектесіп, мектеп өмірін жақсартқың келсе, жұмаға дейін өтінім жібер.",
    category: "opportunity",
    priority: "important",
    targetClasses: ["9A", "10B", "11A"],
    createdAt: "2026-04-17T11:00:00+00:00"
  },
  {
    id: 4,
    title: "Обновлен график консультаций перед олимпиадами",
    titleKz: "Олимпиада алдындағы кеңес беру кестесі жаңартылды",
    content: "Добавлены консультации по математике, биологии и английскому языку.",
    contentKz: "Математика, биология және ағылшын тілі бойынша қосымша кеңестер қосылды.",
    category: "school-wide",
    priority: "normal",
    targetClasses: [],
    createdAt: "2026-04-16T14:00:00+00:00"
  },
  {
    id: 5,
    title: "Волонтерская команда ищет помощников",
    titleKz: "Волонтерлік команда көмекшілер іздейді",
    content: "Нужны ученики для помощи на благотворительной ярмарке и встрече гостей.",
    contentKz: "Қайырымдылық жәрмеңкесіне және қонақтарды қарсы алуға оқушылар қажет.",
    category: "opportunity",
    priority: "normal",
    targetClasses: ["7A", "7B", "8A", "8B", "9A"],
    createdAt: "2026-04-15T10:15:00+00:00"
  },
  {
    id: 6,
    title: "Тихая зона в библиотеке во время экзаменов",
    titleKz: "Емтихан кезінде кітапханада тыныш аймақ",
    content: "С 22 апреля библиотека открывает отдельную зону для подготовки и самостоятельной работы.",
    contentKz: "22 сәуірден бастап кітапханада дайындық пен жеке жұмысқа арналған арнайы аймақ ашылады.",
    category: "school-wide",
    priority: "normal",
    targetClasses: [],
    createdAt: "2026-04-14T08:40:00+00:00"
  },
  {
    id: 7,
    title: "Классные руководители обновили списки проектов",
    titleKz: "Сынып жетекшілері жобалар тізімін жаңартты",
    content: "Проверь свой класс: некоторые проектные группы поменяли время встреч.",
    contentKz: "Өз сыныбыңызды тексеріңіз: кейбір жобалық топтардың кездесу уақыты өзгерді.",
    category: "class-specific",
    priority: "important",
    targetClasses: ["8A", "9A", "10B"],
    createdAt: "2026-04-13T13:20:00+00:00"
  }
];

export const mockEvents: SchoolEvent[] = [
  {
    id: 1,
    title: "Научная ярмарка проектов",
    titleKz: "Ғылыми жобалар жәрмеңкесі",
    shortDescription: "Презентация экспериментов, прототипов и исследовательских стендов.",
    shortDescriptionKz: "Эксперименттер, прототиптер және зерттеу стендтері таныстырылады.",
    fullDescription: "Ученики могут выступить как участники или прийти зрителями. Из-за вместимости зала зрительская регистрация открыта только для отдельных классов.",
    fullDescriptionKz: "Оқушылар қатысушы ретінде қатыса алады немесе көрермен бола алады. Зал сыйымдылығына байланысты көрермен тіркелуі тек кейбір сыныптарға ашық.",
    date: "2026-05-02",
    startTime: "14:00",
    endTime: "17:00",
    location: "Главный зал",
    locationKz: "Бас зал",
    category: "science",
    organizer: "STEM-клуб",
    organizerKz: "STEM клубы",
    coverImage: "https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-29T18:00:00+00:00",
    participantCapacity: 24,
    spectatorCapacity: 80,
    participantApprovedCount: 8,
    spectatorApprovedCount: 39,
    allowedSpectatorClasses: ["8A", "8B", "9A"],
    viewerCanSpectate: true,
    tags: ["STEM", "исследования", "команда"],
    status: "upcoming",
    featured: true
  },
  {
    id: 2,
    title: "Кубок классов по баскетболу",
    titleKz: "Сыныптар арасындағы баскетбол кубогы",
    shortDescription: "Дружеский турнир команд после уроков.",
    shortDescriptionKz: "Сабақтан кейінгі достық командалық турнир.",
    fullDescription: "Классы собирают команды, болельщики поддерживают с трибун. Зрительская регистрация открыта всем.",
    fullDescriptionKz: "Сыныптар команда жинайды, жанкүйерлер трибунадан қолдайды. Көрермен тіркелуі барлығына ашық.",
    date: "2026-04-24",
    startTime: "15:30",
    endTime: "18:00",
    location: "Спортзал",
    locationKz: "Спорт залы",
    category: "sports",
    organizer: "Кафедра физкультуры",
    organizerKz: "Дене шынықтыру кафедрасы",
    coverImage: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-22T17:00:00+00:00",
    participantCapacity: 60,
    spectatorCapacity: 200,
    participantApprovedCount: 34,
    spectatorApprovedCount: 121,
    allowedSpectatorClasses: [],
    viewerCanSpectate: true,
    tags: ["спорт", "команды"],
    status: "upcoming",
    featured: true
  },
  {
    id: 3,
    title: "Дебатный вечер: города будущего",
    titleKz: "Дебат кеші: болашақ қалалары",
    shortDescription: "Структурные дебаты с голосованием зрителей.",
    shortDescriptionKz: "Көрермен дауыс беруімен өтетін құрылымды дебат.",
    fullDescription: "Подготовь аргументы, выступи спикером или зарегистрируйся зрителем, если твой класс в списке.",
    fullDescriptionKz: "Дәлелдер дайындап, спикер бол немесе сыныбың тізімде болса көрермен ретінде тіркел.",
    date: "2026-05-06",
    startTime: "16:00",
    endTime: "18:00",
    location: "Библиотечный форум",
    locationKz: "Кітапхана форумы",
    category: "culture",
    organizer: "Дебатное общество",
    organizerKz: "Дебат қоғамы",
    registrationOpen: true,
    registrationDeadline: "2026-05-03T16:00:00+00:00",
    participantCapacity: 16,
    spectatorCapacity: 70,
    participantApprovedCount: 10,
    spectatorApprovedCount: 28,
    allowedSpectatorClasses: ["9A", "10B", "11A"],
    viewerCanSpectate: false,
    tags: ["дебаты", "лидерство"],
    status: "upcoming",
    featured: false
  },
  {
    id: 4,
    title: "Музыкальный вечер Lyceum Unplugged",
    titleKz: "Lyceum Unplugged музыкалық кеші",
    shortDescription: "Акустические выступления учеников и камерная атмосфера.",
    shortDescriptionKz: "Оқушылардың акустикалық өнер көрсетуі және жайлы атмосфера.",
    fullDescription: "Вечер для вокалистов, инструменталистов и зрителей. Количество мест ограничено.",
    fullDescriptionKz: "Вокалистер, аспапта ойнаушылар және көрермендерге арналған кеш. Орын саны шектеулі.",
    date: "2026-04-28",
    startTime: "17:00",
    endTime: "19:00",
    location: "Актовый зал",
    locationKz: "Акт залы",
    category: "culture",
    organizer: "Музыкальный клуб",
    organizerKz: "Музыка клубы",
    coverImage: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-25T18:00:00+00:00",
    participantCapacity: 18,
    spectatorCapacity: 90,
    participantApprovedCount: 12,
    spectatorApprovedCount: 54,
    allowedSpectatorClasses: ["7A", "8A", "8B", "10B"],
    viewerCanSpectate: true,
    tags: ["музыка", "сцена"],
    status: "upcoming",
    featured: false
  },
  {
    id: 5,
    title: "Эко-двор: весенняя посадка",
    titleKz: "Эко-аула: көктемгі отырғызу",
    shortDescription: "Команды классов обновят школьный двор и клумбы.",
    shortDescriptionKz: "Сынып командалары мектеп ауласы мен гүлзарларды жаңартады.",
    fullDescription: "Практическая волонтерская активность: посадка цветов, маркировка зон и оформление графика ухода.",
    fullDescriptionKz: "Практикалық волонтерлік белсенділік: гүл отырғызу, аймақтарды белгілеу және күтім кестесін жасау.",
    date: "2026-04-26",
    startTime: "12:30",
    endTime: "15:00",
    location: "Школьный двор",
    locationKz: "Мектеп ауласы",
    category: "community",
    organizer: "Eco Team",
    organizerKz: "Eco Team",
    coverImage: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-04-23T18:00:00+00:00",
    participantCapacity: 40,
    spectatorCapacity: 20,
    participantApprovedCount: 26,
    spectatorApprovedCount: 4,
    allowedSpectatorClasses: ["8A", "9A"],
    viewerCanSpectate: true,
    tags: ["волонтерство", "экология"],
    status: "upcoming",
    featured: false
  },
  {
    id: 6,
    title: "Хакатон школьных сервисов",
    titleKz: "Мектеп сервистері хакатоны",
    shortDescription: "Мини-команды проектируют цифровые решения для школы.",
    shortDescriptionKz: "Шағын командалар мектепке арналған цифрлық шешімдер жасайды.",
    fullDescription: "За 4 часа команды предложат идею, прототип и короткую презентацию. Зрители допускаются только из старших классов.",
    fullDescriptionKz: "4 сағат ішінде командалар идея, прототип және қысқа презентация ұсынады. Көрермендер тек жоғары сыныптардан.",
    date: "2026-05-11",
    startTime: "13:00",
    endTime: "17:30",
    location: "IT-кабинет",
    locationKz: "IT кабинеті",
    category: "science",
    organizer: "IT Lab",
    organizerKz: "IT Lab",
    coverImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-05-08T18:00:00+00:00",
    participantCapacity: 30,
    spectatorCapacity: 35,
    participantApprovedCount: 18,
    spectatorApprovedCount: 12,
    allowedSpectatorClasses: ["10B", "11A"],
    viewerCanSpectate: false,
    tags: ["IT", "прототип"],
    status: "upcoming",
    featured: true
  },
  {
    id: 7,
    title: "Благотворительная ярмарка",
    titleKz: "Қайырымдылық жәрмеңкесі",
    shortDescription: "Классы готовят стенды, открытки и мини-активности.",
    shortDescriptionKz: "Сыныптар стендтер, ашықхаттар және шағын белсенділіктер дайындайды.",
    fullDescription: "Средства пойдут на школьные социальные проекты. Можно участвовать с классом или помогать как волонтер.",
    fullDescriptionKz: "Қаражат мектептің әлеуметтік жобаларына бағытталады. Сыныппен қатысуға немесе волонтер болуға болады.",
    date: "2026-05-15",
    startTime: "11:00",
    endTime: "14:00",
    location: "Холл первого этажа",
    locationKz: "Бірінші қабат холы",
    category: "community",
    organizer: "Ученический совет",
    organizerKz: "Оқушылар кеңесі",
    coverImage: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80",
    registrationOpen: true,
    registrationDeadline: "2026-05-12T18:00:00+00:00",
    participantCapacity: 70,
    spectatorCapacity: 250,
    participantApprovedCount: 41,
    spectatorApprovedCount: 88,
    allowedSpectatorClasses: [],
    viewerCanSpectate: true,
    tags: ["волонтерство", "ярмарка"],
    status: "upcoming",
    featured: false
  },
  {
    id: 8,
    title: "Турнир по шахматам",
    titleKz: "Шахмат турнирі",
    shortDescription: "Личный зачет и командные очки для классов.",
    shortDescriptionKz: "Жеке есеп және сыныптарға командалық ұпайлар.",
    fullDescription: "Турнир пройдет по швейцарской системе. Зрительская зона небольшая, поэтому доступна только 7-8 классам.",
    fullDescriptionKz: "Турнир швейцариялық жүйе бойынша өтеді. Көрермен аймағы шағын, сондықтан тек 7-8 сыныптарға қолжетімді.",
    date: "2026-05-20",
    startTime: "15:00",
    endTime: "18:00",
    location: "Кабинет 204",
    locationKz: "204 кабинет",
    category: "science",
    organizer: "Шахматный клуб",
    organizerKz: "Шахмат клубы",
    registrationOpen: true,
    registrationDeadline: "2026-05-17T18:00:00+00:00",
    participantCapacity: 32,
    spectatorCapacity: 24,
    participantApprovedCount: 20,
    spectatorApprovedCount: 11,
    allowedSpectatorClasses: ["7A", "7B", "8A", "8B"],
    viewerCanSpectate: true,
    tags: ["логика", "турнир"],
    status: "upcoming",
    featured: false
  }
];

export const mockReports: EventReport[] = [
  {
    id: 1,
    eventId: 10,
    title: "Эко-день превратил двор в зеленую зону",
    titleKz: "Эко-күн ауланы жасыл аймаққа айналдырды",
    summary: "Ученики посадили 120 цветов, установили 6 станций переработки и составили график ухода.",
    summaryKz: "Оқушылар 120 гүл отырғызып, 6 қайта өңдеу станциясын орнатып, күтім кестесін жасады.",
    results: ["120 цветов посажено", "6 станций переработки установлено", "14 волонтеров отмечены"],
    resultsKz: ["120 гүл отырғызылды", "6 қайта өңдеу станциясы орнатылды", "14 волонтер марапатталды"],
    highlights: ["7C подготовил план двора", "10B помог с логистикой", "Eco Team запустила дежурства"],
    highlightsKz: ["7C аула жоспарын дайындады", "10B логистикаға көмектесті", "Eco Team кезекшілік бастады"],
    gallery: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=80"],
    quote: "Маленькие изменения становятся культурой, когда их видит вся школа.",
    quoteKz: "Кішкентай өзгерістерді бүкіл мектеп көргенде, олар мәдениетке айналады.",
    publishedAt: "2026-04-10T10:00:00+00:00"
  },
  {
    id: 2,
    eventId: 11,
    title: "Дебаты помогли выбрать идеи для школьного двора",
    titleKz: "Дебаттар мектеп ауласына идея таңдауға көмектесті",
    summary: "Команды обсудили безопасность, зоны отдыха и навигацию по школе.",
    summaryKz: "Командалар қауіпсіздік, демалыс аймақтары және мектеп навигациясын талқылады.",
    results: ["Победила команда 9A", "42 зрителя проголосовали", "3 идеи переданы администрации"],
    resultsKz: ["9A командасы жеңді", "42 көрермен дауыс берді", "3 идея әкімшілікке берілді"],
    highlights: ["Лучший аргумент — 10B", "Самая сильная речь — 9A"],
    highlightsKz: ["Үздік дәлел — 10B", "Ең мықты сөз — 9A"],
    gallery: ["https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80"],
    quote: "Хорошая идея становится сильнее, когда ее проверяют вопросами.",
    quoteKz: "Жақсы идея сұрақтар арқылы тексерілгенде күшейеді.",
    publishedAt: "2026-04-08T09:00:00+00:00"
  },
  {
    id: 3,
    eventId: 12,
    title: "Книжный обмен собрал 300 книг",
    titleKz: "Кітап алмасу 300 кітап жинады",
    summary: "Ученики принесли книги, оформили стенды рекомендаций и запустили мини-букклубы.",
    summaryKz: "Оқушылар кітап әкеліп, ұсыныс стендтерін жасап, шағын кітап клубтарын бастады.",
    results: ["300 книг обменяно", "5 новых букклубов", "18 рекомендаций опубликовано"],
    resultsKz: ["300 кітап алмастырылды", "5 жаңа кітап клубы", "18 ұсыныс жарияланды"],
    highlights: ["8A оформил лучший стенд", "7B собрал самую большую подборку"],
    highlightsKz: ["8A үздік стенд жасады", "7B ең үлкен топтама жинады"],
    gallery: ["https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80"],
    publishedAt: "2026-04-02T12:00:00+00:00"
  }
];

export const mockApplications: EventApplication[] = [
  { id: 1, userId: 1, eventId: 1, applicationType: "spectator", status: "approved", createdAt: "2026-04-18T12:00:00+00:00", event: mockEvents[0] },
  { id: 2, userId: 1, eventId: 2, applicationType: "participant", status: "pending", createdAt: "2026-04-17T15:00:00+00:00", event: mockEvents[1] },
  { id: 3, userId: 1, eventId: 4, applicationType: "spectator", status: "approved", createdAt: "2026-04-16T09:30:00+00:00", event: mockEvents[3] },
  { id: 4, userId: 1, eventId: 5, applicationType: "participant", status: "waitlisted", createdAt: "2026-04-15T11:20:00+00:00", event: mockEvents[4] },
  { id: 5, userId: 1, eventId: 8, applicationType: "spectator", status: "pending", createdAt: "2026-04-14T16:10:00+00:00", event: mockEvents[7] }
];

export const mockNotifications: AppNotification[] = [
  { id: 1, userId: 1, title: "Заявка на научную ярмарку одобрена", titleKz: "Ғылыми жәрмеңкеге өтінім мақұлданды", message: "Ты зарегистрирована как зритель. Не забудь прийти за 10 минут до начала.", messageKz: "Сіз көрермен ретінде тіркелдіңіз. Басталардан 10 минут бұрын келуді ұмытпаңыз.", isRead: false, type: "application", createdAt: "2026-04-18T13:00:00+00:00" },
  { id: 2, userId: 1, title: "Баскетбольный кубок закрывается завтра", titleKz: "Баскетбол кубогына тіркелу ертең жабылады", message: "Если хочешь участвовать, отправь заявку сегодня.", messageKz: "Қатысқыңыз келсе, бүгін өтінім жіберіңіз.", isRead: false, type: "event", createdAt: "2026-04-18T09:00:00+00:00" },
  { id: 3, userId: 1, title: "Опубликован отчет Eco Day", titleKz: "Eco Day есебі жарияланды", message: "Посмотри результаты и лучшие моменты прошедшего события.", messageKz: "Өткен іс-шараның нәтижелері мен үздік сәттерін қараңыз.", isRead: true, type: "report", createdAt: "2026-04-10T12:00:00+00:00" },
  { id: 4, userId: 1, title: "Музыкальный вечер открыт для 8A", titleKz: "Музыкалық кеш 8A үшін ашық", message: "Ты можешь зарегистрироваться зрителем или участником.", messageKz: "Сіз көрермен немесе қатысушы ретінде тіркеле аласыз.", isRead: false, type: "event", createdAt: "2026-04-16T10:00:00+00:00" }
];

const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

Object.assign(mockAnnouncements.find(item => item.id === 2) ?? {}, { imageUrl: photo("photo-1519389950473-47ba0277781c") });
Object.assign(mockAnnouncements.find(item => item.id === 3) ?? {}, { imageUrl: photo("photo-1521737604893-d14cc237f11d") });
Object.assign(mockAnnouncements.find(item => item.id === 4) ?? {}, { imageUrl: photo("photo-1516321318423-f06f85e504b3") });
Object.assign(mockAnnouncements.find(item => item.id === 5) ?? {}, { imageUrl: photo("photo-1559027615-cd4628902d4a") });
Object.assign(mockAnnouncements.find(item => item.id === 6) ?? {}, { imageUrl: photo("photo-1521587760476-6c12a4b040da") });
Object.assign(mockAnnouncements.find(item => item.id === 7) ?? {}, { imageUrl: photo("photo-1509062522246-3755977927d7") });
Object.assign(mockEvents.find(item => item.id === 3) ?? {}, { coverImage: photo("photo-1523580494863-6f3031224c94") });
Object.assign(mockEvents.find(item => item.id === 8) ?? {}, { coverImage: photo("photo-1529699211952-734e80c4d42b") });

mockAnnouncements.push(
  {
    id: 8,
    title: "Открыта запись на весенние мастерские",
    titleKz: "Көктемгі шеберханаларға жазылу ашылды",
    content: "На этой неделе запускаются мастерские по фотографии, публичным выступлениям, робототехнике и школьному медиа. Каждый ученик может выбрать одно направление, а кураторы помогут собрать портфолио или мини-проект к финальному показу.",
    contentKz: "Осы аптада фотография, көпшілік алдында сөйлеу, робототехника және мектеп медиа бағыттары бойынша шеберханалар басталады.",
    category: "opportunity",
    priority: "important",
    imageUrl: photo("photo-1497493292307-31c376b6e479"),
    targetClasses: ["8A", "8B", "9A", "10B", "11A"],
    createdAt: "2026-04-20T08:30:00+00:00"
  },
  {
    id: 9,
    title: "Неделя профориентации для старших классов",
    titleKz: "Жоғары сыныптарға арналған мамандық апталығы",
    content: "Университетские гости, выпускники и школьный психолог проведут встречи о выборе специальности, портфолио, олимпиадах и грантах. Часть встреч открыта для зрителей из 9 классов.",
    contentKz: "Университет қонақтары, түлектер және мектеп психологы мамандық таңдау, портфолио, олимпиадалар және гранттар туралы кездесулер өткізеді.",
    category: "school-wide",
    priority: "normal",
    imageUrl: photo("photo-1523240795612-9a054b0db644"),
    targetClasses: ["9A", "10B", "11A"],
    createdAt: "2026-04-20T10:10:00+00:00"
  },
  {
    id: 10,
    title: "Классные команды готовят стенды ко Дню школы",
    titleKz: "Сынып командалары мектеп күніне стенд дайындайды",
    content: "Каждый класс выбирает тему стенда: история класса, любимые проекты, спортивные победы или полезные идеи для школы. Лучшие стенды попадут в отчет и будут показаны на главной странице.",
    contentKz: "Әр сынып стенд тақырыбын таңдайды: сынып тарихы, сүйікті жобалар, спорттық жеңістер немесе мектепке пайдалы идеялар.",
    category: "class-specific",
    priority: "normal",
    imageUrl: photo("photo-1517245386807-bb43f82c33c4"),
    targetClasses: ["7A", "7B", "8A", "8B", "9A", "10B", "11A"],
    createdAt: "2026-04-19T12:45:00+00:00"
  },
  {
    id: 11,
    title: "Обновлены правила регистрации зрителей",
    titleKz: "Көрермендерді тіркеу ережелері жаңартылды",
    content: "Если мероприятие ограничено по классам, зрительская заявка будет доступна только ученикам из списка. Участником можно подать заявку отдельно, если организатор оставил такую роль открытой.",
    contentKz: "Іс-шара сыныптар бойынша шектелсе, көрермен өтінімі тек тізімдегі оқушыларға қолжетімді болады.",
    category: "school-wide",
    priority: "important",
    imageUrl: photo("photo-1450101499163-c8848c66ca85"),
    targetClasses: [],
    createdAt: "2026-04-19T15:00:00+00:00"
  }
);

mockEvents.push(
  {
    id: 9,
    title: "Форум профессий: медицина, IT и инженерия",
    titleKz: "Мамандықтар форумы: медицина, IT және инженерия",
    shortDescription: "Старшеклассники встречаются с выпускниками и собирают карту карьерных шагов.",
    shortDescriptionKz: "Жоғары сынып оқушылары түлектермен кездесіп, мансап қадамдарының картасын жасайды.",
    fullDescription: "Форум состоит из трех треков: медицина и биотехнологии, IT и цифровые продукты, инженерия и городская среда. Участники готовят вопросы заранее, а зрители могут прийти на панельные сессии, если их класс есть в списке допуска.",
    fullDescriptionKz: "Форум үш бағыттан тұрады: медицина және биотехнология, IT және цифрлық өнімдер, инженерия және қалалық орта.",
    date: "2026-05-23",
    startTime: "14:30",
    endTime: "17:30",
    location: "Конференц-зал",
    locationKz: "Конференц-зал",
    category: "science",
    organizer: "Career Office",
    organizerKz: "Career Office",
    coverImage: photo("photo-1552664730-d307ca884978"),
    registrationOpen: true,
    registrationDeadline: "2026-05-20T18:00:00+00:00",
    participantCapacity: 45,
    spectatorCapacity: 100,
    participantApprovedCount: 19,
    spectatorApprovedCount: 43,
    allowedSpectatorClasses: ["9A", "10B", "11A"],
    viewerCanSpectate: false,
    tags: ["career", "университет", "портфолио"],
    status: "upcoming",
    featured: true
  },
  {
    id: 10,
    title: "Театральная лаборатория: один день репетиции",
    titleKz: "Театр зертханасы: бір күндік дайындық",
    shortDescription: "Команды ставят короткие сцены по школьным историям и учатся работать с голосом.",
    shortDescriptionKz: "Командалар мектеп оқиғалары бойынша қысқа сахналар қойып, дауыспен жұмыс істеуді үйренеді.",
    fullDescription: "Лаборатория подходит для тех, кто хочет попробовать актерское мастерство, сценографию, свет, звук или работу режиссера. Финальный показ пройдет в конце дня, зрительские места открыты для 8-11 классов.",
    fullDescriptionKz: "Зертхана актерлік шеберлік, сценография, жарық, дыбыс немесе режиссерлік жұмысты байқап көргісі келетіндерге арналған.",
    date: "2026-05-27",
    startTime: "13:00",
    endTime: "18:00",
    location: "Малая сцена",
    locationKz: "Кіші сахна",
    category: "culture",
    organizer: "Drama Studio",
    organizerKz: "Drama Studio",
    coverImage: photo("photo-1503095396549-807759245b35"),
    registrationOpen: true,
    registrationDeadline: "2026-05-24T18:00:00+00:00",
    participantCapacity: 28,
    spectatorCapacity: 75,
    participantApprovedCount: 14,
    spectatorApprovedCount: 21,
    allowedSpectatorClasses: ["8A", "8B", "9A", "10B", "11A"],
    viewerCanSpectate: true,
    tags: ["театр", "сцена", "культура"],
    status: "upcoming",
    featured: false
  },
  {
    id: 11,
    title: "Медиахакатон: школьный подкаст за 3 часа",
    titleKz: "Медиа-хакатон: 3 сағатта мектеп подкасты",
    shortDescription: "Участники пишут сценарий, записывают звук и собирают первый выпуск.",
    shortDescriptionKz: "Қатысушылар сценарий жазып, дыбыс жазып, алғашқы шығарылымды жинайды.",
    fullDescription: "Медиахакатон научит быстро выбирать тему, распределять роли, записывать интервью и делать короткий монтаж. Лучшие выпуски будут опубликованы в школьном дайджесте.",
    fullDescriptionKz: "Медиа-хакатон тақырып таңдауды, рөлдерді бөлуді, сұхбат жазуды және қысқа монтаж жасауды үйретеді.",
    date: "2026-05-29",
    startTime: "15:00",
    endTime: "18:00",
    location: "Медиацентр",
    locationKz: "Медиаорталық",
    category: "culture",
    organizer: "School Media",
    organizerKz: "School Media",
    coverImage: photo("photo-1478737270239-2f02b77fc618"),
    registrationOpen: true,
    registrationDeadline: "2026-05-26T18:00:00+00:00",
    participantCapacity: 24,
    spectatorCapacity: 20,
    participantApprovedCount: 9,
    spectatorApprovedCount: 5,
    allowedSpectatorClasses: ["9A", "10B", "11A"],
    viewerCanSpectate: false,
    tags: ["media", "podcast", "interview"],
    status: "upcoming",
    featured: false
  },
  {
    id: 12,
    title: "Волейбольная лига параллелей",
    titleKz: "Параллельдер арасындағы волейбол лигасы",
    shortDescription: "Матчи между параллелями с отдельным рейтингом болельщиков.",
    shortDescriptionKz: "Параллельдер арасындағы матчтар және жанкүйерлер рейтингі.",
    fullDescription: "Команды играют короткие матчи до 15 очков. Зрители поддерживают свою параллель, а организаторы отмечают не только победы, но и спортивное поведение команд.",
    fullDescriptionKz: "Командалар 15 ұпайға дейін қысқа матчтар ойнайды. Көрермендер өз параллелін қолдайды.",
    date: "2026-06-03",
    startTime: "15:30",
    endTime: "18:30",
    location: "Спортзал",
    locationKz: "Спорт залы",
    category: "sports",
    organizer: "PE Department",
    organizerKz: "Дене шынықтыру кафедрасы",
    coverImage: photo("photo-1592656094267-764a45160876"),
    registrationOpen: true,
    registrationDeadline: "2026-05-31T18:00:00+00:00",
    participantCapacity: 72,
    spectatorCapacity: 180,
    participantApprovedCount: 38,
    spectatorApprovedCount: 72,
    allowedSpectatorClasses: [],
    viewerCanSpectate: true,
    tags: ["спорт", "лига", "команды"],
    status: "upcoming",
    featured: false
  },
  {
    id: 13,
    title: "Лаборатория робототехники: автономный маршрут",
    titleKz: "Робототехника зертханасы: автономды маршрут",
    shortDescription: "Команды программируют роботов, чтобы пройти трассу без ручного управления.",
    shortDescriptionKz: "Командалар роботтарды қолмен басқармай трассадан өткізуге бағдарламалайды.",
    fullDescription: "Участники работают с датчиками, логикой движения и быстрыми тестами. Зрители из старших классов смогут наблюдать за финальными заездами и голосовать за самый надежный алгоритм.",
    fullDescriptionKz: "Қатысушылар датчиктермен, қозғалыс логикасымен және жылдам тесттермен жұмыс істейді.",
    date: "2026-06-10",
    startTime: "14:00",
    endTime: "17:00",
    location: "STEM Lab",
    locationKz: "STEM Lab",
    category: "science",
    organizer: "Robotics Team",
    organizerKz: "Robotics Team",
    coverImage: photo("photo-1485827404703-89b55fcc595e"),
    registrationOpen: true,
    registrationDeadline: "2026-06-07T18:00:00+00:00",
    participantCapacity: 20,
    spectatorCapacity: 45,
    participantApprovedCount: 11,
    spectatorApprovedCount: 18,
    allowedSpectatorClasses: ["8A", "9A", "10B", "11A"],
    viewerCanSpectate: true,
    tags: ["robotics", "STEM", "programming"],
    status: "upcoming",
    featured: true
  }
);

mockReports.push(
  {
    id: 4,
    eventId: 13,
    title: "Медиахакатон выпустил первый школьный подкаст",
    titleKz: "Медиа-хакатон алғашқы мектеп подкастын шығарды",
    summary: "За один день команды придумали рубрики, записали интервью с учителями и собрали короткие выпуски о школьных событиях.",
    summaryKz: "Бір күн ішінде командалар айдар ойлап тауып, мұғалімдерден сұхбат жазып, мектеп оқиғалары туралы қысқа шығарылымдар жинады.",
    results: ["6 пилотных выпусков записано", "18 учеников попробовали монтаж", "3 выпуска выбраны для публикации"],
    resultsKz: ["6 пилоттық шығарылым жазылды", "18 оқушы монтаж жасап көрді", "3 шығарылым жариялануға таңдалды"],
    highlights: ["10B собрал лучший саунд-дизайн", "9A взял самое живое интервью", "Медиацентр запустил редакционный календарь"],
    highlightsKz: ["10B үздік саунд-дизайн жасады", "9A ең әсерлі сұхбат алды", "Медиаорталық редакциялық күнтізбе бастады"],
    gallery: [photo("photo-1478737270239-2f02b77fc618"), photo("photo-1495020689067-958852a7765e")],
    quote: "Когда ученики слышат свой голос в общем проекте, школа становится ближе.",
    quoteKz: "Оқушылар ортақ жобада өз дауысын естігенде, мектеп жақындай түседі.",
    publishedAt: "2026-04-12T11:00:00+00:00"
  },
  {
    id: 5,
    eventId: 14,
    title: "Баскетбольный кубок собрал полный спортзал",
    titleKz: "Баскетбол кубогы спорт залын толтырды",
    summary: "Классы подготовили команды поддержки, а финальная игра решила победителя только в последнюю минуту.",
    summaryKz: "Сыныптар қолдау командаларын дайындады, ал финал жеңімпазды соңғы минутта анықтады.",
    results: ["8 команд участвовали", "124 зрителя пришли на финал", "11A выиграл кубок параллелей"],
    resultsKz: ["8 команда қатысты", "124 көрермен финалға келді", "11A параллельдер кубогын жеңді"],
    highlights: ["Лучший капитан - 8A", "Самая громкая поддержка - 9A", "Fair Play получил 10B"],
    highlightsKz: ["Үздік капитан - 8A", "Ең белсенді қолдау - 9A", "Fair Play - 10B"],
    gallery: [photo("photo-1546519638-68e109498ffc"), photo("photo-1519861531473-9200262188bf")],
    quote: "Спортивный день получился не про счет, а про чувство команды.",
    quoteKz: "Спорт күні есеп туралы емес, команда сезімі туралы болды.",
    publishedAt: "2026-04-06T13:00:00+00:00"
  }
);

mockApplications.push(
  { id: 6, userId: 1, eventId: 10, applicationType: "participant", status: "approved", createdAt: "2026-04-19T10:10:00+00:00", event: mockEvents.find(item => item.id === 10) },
  { id: 7, userId: 1, eventId: 12, applicationType: "spectator", status: "pending", createdAt: "2026-04-19T11:45:00+00:00", event: mockEvents.find(item => item.id === 12) },
  { id: 8, userId: 1, eventId: 13, applicationType: "participant", status: "approved", createdAt: "2026-04-20T09:15:00+00:00", event: mockEvents.find(item => item.id === 13) }
);

mockNotifications.push(
  { id: 5, userId: 1, title: "Новая мастерская доступна твоему классу", titleKz: "Жаңа шеберхана сыныбыңызға қолжетімді", message: "Театральная лаборатория открыла зрительские места для 8A. Можно подать заявку до 24 мая.", messageKz: "Театр зертханасы 8A үшін көрермен орындарын ашты.", isRead: false, type: "event", createdAt: "2026-04-20T14:00:00+00:00" },
  { id: 6, userId: 1, title: "Подкаст-медиацентр ищет участников", titleKz: "Подкаст медиаорталығы қатысушылар іздейді", message: "Если хочешь попробовать интервью или монтаж, открой событие медиахакатона.", messageKz: "Сұхбат немесе монтаж жасап көргіңіз келсе, медиа-хакатон іс-шарасын ашыңыз.", isRead: true, type: "opportunity", createdAt: "2026-04-20T09:40:00+00:00" },
  { id: 7, userId: 1, title: "Отчет о баскетбольном кубке опубликован", titleKz: "Баскетбол кубогы туралы есеп жарияланды", message: "Посмотри лучшие моменты финала и список отмеченных команд.", messageKz: "Финалдың үздік сәттері мен марапатталған командаларды қараңыз.", isRead: false, type: "report", createdAt: "2026-04-19T18:00:00+00:00" }
);
